"""add-allow-null-attribute

Revision ID: 6e9129acd194
Revises: 8b55887e6e2b
Create Date: 2021-06-08 00:37:31.024424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9129acd194'
down_revision = '8b55887e6e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'profile_image',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Artist', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Artist', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('ArtistFollow', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('OrgArtist', 'artist_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('PlayList', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PlayList', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('PlayListLike', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PlayListSong', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Song', 'play',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Song', 'profile_image',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Song', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Song', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('User', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('User', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('User', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('UserArtist', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('UserSound', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('UserSound', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserSound', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('UserSound', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('UserArtist', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('User', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('User', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('User', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('Song', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Song', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Song', 'profile_image',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Song', 'play',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('PlayListSong', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PlayListLike', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PlayList', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('PlayList', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('OrgArtist', 'artist_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ArtistFollow', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Artist', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Artist', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Artist', 'profile_image',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
